Unhandled Exception occured in security RI Message: An error occured in creating the User could not insert: [gov.nih.nci.security.authorization.domainobjects.User] StackTrace: gov.nih.nci.security.exceptions.CSTransactionException: An error occured in creating the User could not insert: [gov.nih.nci.security.authorization.domainobjects.User] at gov.nih.nci.security.dao.AuthorizationDAOImpl.createObject(AuthorizationDAOImpl.java:2603) at gov.nih.nci.security.provisioning.UserProvisioningManagerImpl.createUser(UserProvisioningManagerImpl.java:624) at gov.nih.nci.security.ri.struts.actions.CreateEmployeeAction.doAuthorization(CreateEmployeeAction.java:77) at gov.nih.nci.security.ri.struts.actions.CreateEmployeeAction.executeSecureWorkflow(CreateEmployeeAction.java:48) at gov.nih.nci.security.ri.struts.actions.SecureAction.executeWorkflow(SecureAction.java:58) at gov.nih.nci.security.ri.struts.actions.BaseAction.execute(BaseAction.java:58) at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484) at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274) at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482) at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at javax.servlet.http.HttpServlet.service(HttpServlet.java:810) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:214) at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104) at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520) at org.apache.catalina.core.StandardContextValve.invokeInternal(StandardContextValve.java:198) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:152) at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104) at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:72) at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102) at org.jboss.web.tomcat.security.JBossSecurityMgrRealm.invoke(JBossSecurityMgrRealm.java:275) at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102) at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117) at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102) at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104) at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520) at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:929) at org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:160) at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:799) at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:705) at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:577) at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:683) at java.lang.Thread.run(Thread.java:534) Caused by: net.sf.hibernate.exception.ConstraintViolationException: could not insert: [gov.nih.nci.security.authorization.domainobjects.User] at net.sf.hibernate.exception.ErrorCodeConverter.convert(ErrorCodeConverter.java:73) at net.sf.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:30) at net.sf.hibernate.persister.AbstractEntityPersister.convert(AbstractEntityPersister.java:1332) at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:542) at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:428) at net.sf.hibernate.impl.ScheduledIdentityInsertion.execute(ScheduledIdentityInsertion.java:29) at net.sf.hibernate.impl.SessionImpl.doSave(SessionImpl.java:941) at net.sf.hibernate.impl.SessionImpl.doSave(SessionImpl.java:866) at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:784) at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:747) at gov.nih.nci.security.dao.AuthorizationDAOImpl.createObject(AuthorizationDAOImpl.java:2585) ... 39 more Caused by: java.sql.SQLException: Invalid argument value, message from server: "Duplicate entry '' for key 2" at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1905) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1109) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1203) at com.mysql.jdbc.Connection.execSQL(Connection.java:2090) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1680) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1527) at com.mchange.v2.sql.filter.FilterPreparedStatement.executeUpdate(FilterPreparedStatement.java:71) at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:520) ... 46 more 
